title: Project Trident
author:
  name: Project Trident Team
  email: 'core@project-trident.org'
metadata:
    description: 'Bootstrap 3.0 template by Template-help.com, ported to Grav.'
    
# Site settings
title: Project Trident
email: core@project-trident.org
description: "Project Trident is a secure and reliable desktop-based operating system"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  -  url: "#"
     icon: facebook.png
  -  url: "#"
     icon: gplus.png
  -  url: "#"
     icon: twitter.png
  -  url: "#"
     icon: rss.png    

copyright: 
  line1: Untitled
  line2: Design:
  url: http://html5up.net
  url_label: HTML5 UP
    
logo:
  text1: "Photographer"
  text2: "by HTML5 UP"

# Main Menu
menu:
  - text: "submenu"
    submenu:
      - text: "info"
        link: "#"
      - text: "profile"
        link: "#"  
      - text: "news"
        link: "#"
        submenu:
          - text: "fresh"
            link: "#"
          - text: "archive"
            link: "#"  
    link: "#" 
