title: Project Trident
author:
  name: Project Trident Team
  email: 'core@project-trident.org'
metadata:
    description: 'Project Trident: Privacy-focused OS'
    
# Site settings
title: Project Trident
email: core@project-trident.org
description: "Project Trident is a secure and reliable desktop-based operating system"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  -  url: "https://www.twitch.tv/thetridentproject"
     icon: twitch.png
  -  url: "https://www.reddit.com/r/projecttrident/"
     icon: reddit.png
  -  url: "https://twitter.com/TridentProject"
     icon: twitter.png

copyright: 
  line1: Untitled
  line2: Design:
  url: http://html5up.net
  url_label: HTML5 UP
    
logo:
  text1: "Project Trident"
  text2: ""

# Main Menu
menu:
  - text: "More"
    submenu:
      - text: "FAQ"
        link: "/faq"
      - text: "Forums"
        link: "https://discourse.trueos.org"
